<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { ElMessage } from 'element-plus'; import { api } from '../api'; import { useAuthStore } from '../stores/auth'
const auth=useAuthStore();const tab=ref('models');const models=ref<any[]>([]);const prompts=ref<any[]>([]);const dialog=ref(false);const form=ref({name:'DeepSeek 主模型',provider:'deepseek',api_key:'',base_url:'https://api.deepseek.com/v1',model_name:'deepseek-chat',temperature:0.1,max_tokens:4096})
async function load(){if(auth.user?.role==='admin')models.value=(await api.get('/model-configs')).data.data;prompts.value=(await api.get('/prompt-templates')).data.data}
async function saveModel(){await api.post('/model-configs',form.value);dialog.value=false;ElMessage.success('模型配置已保存');load()}
async function activate(id:string){await api.post(`/model-configs/${id}/active`);ElMessage.success('已切换模型');load()}
onMounted(load)
</script>
<template><div class="page-head"><div><h1>系统配置</h1><p>模型、API 密钥与合同 Prompt 模板集中管理</p></div></div><el-tabs v-model="tab"><el-tab-pane v-if="auth.user?.role==='admin'" label="模型配置" name="models"><div class="toolbar"><el-button type="primary" @click="dialog=true">添加模型</el-button></div><section class="panel table-panel"><el-table :data="models"><el-table-column prop="name" label="配置名称"/><el-table-column prop="provider" label="服务商"/><el-table-column prop="model_name" label="模型"/><el-table-column prop="api_key_masked" label="API Key"/><el-table-column label="状态"><template #default="s"><el-tag :type="s.row.is_active?'success':'info'">{{s.row.is_active?'使用中':'未启用'}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="s"><el-button text type="primary" @click="activate(s.row.id)">启用</el-button></template></el-table-column></el-table></section></el-tab-pane><el-tab-pane label="Prompt 模板" name="prompts"><section class="panel table-panel"><el-table :data="prompts"><el-table-column prop="name" label="模板名称"/><el-table-column prop="contract_type" label="合同类型"/><el-table-column prop="stage" label="Agent 阶段"/><el-table-column prop="version" label="版本" width="80"/><el-table-column label="状态"><template #default="s"><el-tag>{{s.row.is_enabled?'启用':'停用'}}</el-tag></template></el-table-column></el-table></section></el-tab-pane></el-tabs><el-dialog v-model="dialog" title="添加外部模型" width="520"><el-form label-position="top"><el-form-item label="配置名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="服务商"><el-select v-model="form.provider"><el-option label="DeepSeek" value="deepseek"/><el-option label="OpenAI" value="openai"/><el-option label="通义千问" value="qwen"/><el-option label="Gemini" value="gemini"/></el-select></el-form-item><el-form-item label="API Key"><el-input v-model="form.api_key" type="password" show-password/></el-form-item><el-form-item label="Base URL"><el-input v-model="form.base_url"/></el-form-item><el-form-item label="模型名称"><el-input v-model="form.model_name"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="saveModel">保存并验证</el-button></template></el-dialog></template>
